name: CI (build, lint, test, bump)

on:
  workflow_dispatch: # Allows manual run.

  push:
    branches:
      - main
    paths:
      - 'go.*'
      - '**/*.go'
      - 'src/**'
      - '.github/workflows/*.yml'
      - '.github/goreleaser*.yaml'
      - '.golangci.yml'

  pull_request:
    branches:
      - '**'
    paths:
      - 'go.*'
      - '**/*.go'
      - 'src/**'
      - '.golangci.yml'
      - '.github/workflows/*.yml'
      - '.github/goreleaser*.yaml'

jobs:
  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      code_coverage: true
      min_test_coverage_percent: 80
